// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHomeAutomationSystemSimulator.DbContexts;

#nullable disable

namespace SmartHomeAutomationSystemSimulator.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251113131847_smartDevice03")]
    partial class smartDevice03
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartHomeAutomationSystemSimulator.Models.SmartDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("InstalledDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOn")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PowerConsumption")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SmartDevices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InstalledDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOn = false,
                            Location = "Living Room",
                            Manufacturer = "Philips",
                            Name = "Smart Light",
                            PowerConsumption = 15.0,
                            Type = "Lighting"
                        },
                        new
                        {
                            Id = 2,
                            InstalledDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOn = false,
                            Location = "Hallway",
                            Manufacturer = "Nest",
                            Name = "Smart Thermostat",
                            PowerConsumption = 40.0,
                            Type = "HVAC"
                        },
                        new
                        {
                            Id = 3,
                            InstalledDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOn = false,
                            Location = "Front Door",
                            Manufacturer = "August",
                            Name = "Smart Door Lock",
                            PowerConsumption = 10.0,
                            Type = "Security"
                        },
                        new
                        {
                            Id = 4,
                            InstalledDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOn = false,
                            Location = "Garage",
                            Manufacturer = "Ring",
                            Name = "Smart Camera",
                            PowerConsumption = 20.0,
                            Type = "Security"
                        },
                        new
                        {
                            Id = 5,
                            InstalledDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOn = false,
                            Location = "Bedroom",
                            Manufacturer = "Amazon",
                            Name = "Smart Speaker",
                            PowerConsumption = 25.0,
                            Type = "Audio"
                        },
                        new
                        {
                            Id = 6,
                            InstalledDate = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOn = false,
                            Location = "Kitchen",
                            Manufacturer = "TP-Link",
                            Name = "Smart Plug",
                            PowerConsumption = 5.0,
                            Type = "Power"
                        },
                        new
                        {
                            Id = 7,
                            InstalledDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOn = false,
                            Location = "Kitchen",
                            Manufacturer = "Samsung",
                            Name = "Smart Refrigerator",
                            PowerConsumption = 200.0,
                            Type = "Appliance"
                        },
                        new
                        {
                            Id = 8,
                            InstalledDate = new DateTime(2024, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOn = false,
                            Location = "Laundry Room",
                            Manufacturer = "LG",
                            Name = "Smart Washer",
                            PowerConsumption = 150.0,
                            Type = "Appliance"
                        },
                        new
                        {
                            Id = 9,
                            InstalledDate = new DateTime(2024, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOn = false,
                            Location = "Living Room",
                            Manufacturer = "Sony",
                            Name = "Smart TV",
                            PowerConsumption = 120.0,
                            Type = "Entertainment"
                        },
                        new
                        {
                            Id = 10,
                            InstalledDate = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOn = false,
                            Location = "Bedroom",
                            Manufacturer = "Dyson",
                            Name = "Smart Air Purifier",
                            PowerConsumption = 60.0,
                            Type = "Environment"
                        },
                        new
                        {
                            Id = 11,
                            InstalledDate = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOn = false,
                            Location = "Kitchen",
                            Manufacturer = "Breville",
                            Name = "Smart Coffee Maker",
                            PowerConsumption = 1000.0,
                            Type = "Appliance"
                        },
                        new
                        {
                            Id = 12,
                            InstalledDate = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOn = false,
                            Location = "Living Room",
                            Manufacturer = "Xiaomi",
                            Name = "Smart Fan",
                            PowerConsumption = 50.0,
                            Type = "Cooling"
                        },
                        new
                        {
                            Id = 13,
                            InstalledDate = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOn = false,
                            Location = "Living Room",
                            Manufacturer = "iRobot",
                            Name = "Smart Vacuum",
                            PowerConsumption = 70.0,
                            Type = "Cleaning"
                        },
                        new
                        {
                            Id = 14,
                            InstalledDate = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOn = false,
                            Location = "Front Door",
                            Manufacturer = "Ring",
                            Name = "Smart Doorbell",
                            PowerConsumption = 10.0,
                            Type = "Security"
                        },
                        new
                        {
                            Id = 15,
                            InstalledDate = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOn = false,
                            Location = "Kitchen",
                            Manufacturer = "Ninja",
                            Name = "Smart Blender",
                            PowerConsumption = 300.0,
                            Type = "Appliance"
                        },
                        new
                        {
                            Id = 16,
                            InstalledDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOn = false,
                            Location = "Kitchen",
                            Manufacturer = "Samsung",
                            Name = "Smart Oven",
                            PowerConsumption = 2500.0,
                            Type = "Appliance"
                        },
                        new
                        {
                            Id = 17,
                            InstalledDate = new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOn = false,
                            Location = "Bedroom",
                            Manufacturer = "Govee",
                            Name = "Smart Lights Strip",
                            PowerConsumption = 20.0,
                            Type = "Lighting"
                        },
                        new
                        {
                            Id = 18,
                            InstalledDate = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOn = false,
                            Location = "Living Room",
                            Manufacturer = "LG",
                            Name = "Smart Air Conditioner",
                            PowerConsumption = 1500.0,
                            Type = "Cooling"
                        },
                        new
                        {
                            Id = 19,
                            InstalledDate = new DateTime(2024, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOn = false,
                            Location = "Bedroom",
                            Manufacturer = "Levoit",
                            Name = "Smart Humidifier",
                            PowerConsumption = 30.0,
                            Type = "Environment"
                        },
                        new
                        {
                            Id = 20,
                            InstalledDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOn = false,
                            Location = "Garage",
                            Manufacturer = "Chamberlain",
                            Name = "Smart Garage Door",
                            PowerConsumption = 15.0,
                            Type = "Security"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
